lidar_align:
  ros__parameters:
    # Input
    input_bag_path: ""
    input_csv_path: ""
    odom_source: "odometry"  # "tf", "pose_stamped", "odometry", or "csv"

    # Pointcloud / TF selection
    pointcloud_topic: "/sensing/lidar/front/pointcloud_raw_ex"
    tf_topic: "/tf"
    tf_static_topic: "/tf_static"
    tf_parent_frame: "map"
    tf_child_frame: "base_link"
    use_tf_static: false
    pose_topic: "/localization/kinematic_state"  # pose topic (odom_source: "pose_stamped" or "odometry" の場合に使用)

    # Loader
    use_n_scans: 1000000

    # Lidar / timing
    motion_compensation: false # Hesai AT128のような回転式ではないLiDARの場合はfalseで問題ない
    estimate_point_times: false # pointcloudの各点の時間を推定するか。LiDARのRPMと点群の順序がわかっている場合はtrueにするとより正確な補正ができる
    global_point_time_offset: 0.0
    clockwise_lidar: false
    lidar_rpm: 600.0
    min_return_intensity: -1.0 # intensityがこの値以上の点のみを使用。-1.0の場合は全ての点を使用。0.0にするとほとんどの点が除外されたので-1.0にデフォルトを変更

    # Optimizer
    local: true
    inital_guess: [6.385, -0.025, 1.100, 0.0, 0.0, 0.0] # frontの場合[x, y, z, roll, pitch, yaw]: lidarの初期位置と姿勢の推定値。単位はmとrad
    # initial_guess: [-0.630, 0.025, 1.500, 0.0, 0.0, 3.14159] # backの場合[x, y, z, roll, pitch, yaw]: lidarの初期位置と姿勢の推定値。単位はmとrad
    max_time_offset: 0.10
    angular_range: 0.35
    translation_range: 1.50
    max_evals: 400.0
    xtol: 1.0e-4

    # KNN / cost
    knn_batch_size: 500
    knn_k: 10
    global_knn_max_dist: 2.0
    local_knn_max_dist: 0.5

    # Time calibration
    time_cal: true

    # Output
    output_pointcloud_path: "/tmp/lidar_align_results/aligned_points.ply"
    output_calibration_path: "/tmp/lidar_align_results/calibration.txt"
